### ISSUE TITLE
Unit-testing for Django Client Framework's model api

### ISSUE THREAD

**Issue by ylilarry** [kaleido-public/quests#8]
### Quest

teamsize: 1
implement before: Fri, May 7

The Django Client Framework was originally a part of the cozybear project. Although DCF has been separated out as an independent project, the unit test was stuck in the old cozybear source code. Your task is to write unit tests for the model API to ensure that the API works exactly as specified in the two sections of the documentation: 

1. [Basic usage](https://cozybearca.github.io/django-client-framework-docs/html/intro/index.html#supported-methods-of-the-restful-api) 
2. [Permissions for RESTful requests](https://cozybearca.github.io/django-client-framework-docs/html/intro/index.html#permissions-for-restful-requests)

I have set up a template test project for you to work on. For that, see the staging branch of the [DCF repo]( https://github.com/cozybearca/django-client-framework). The unit tests are in the `./unit-tests` directory. It is recommended that you use [Docker](https://www.docker.com/products/docker-desktop) to run it. Simply `cd unit-tests && make`.

To test DCF, we need to create some models that are only used for testing purposes. Therefore, there needs to be a django app named `dcf_test_app` in which these models are defined.

### Requirement

1. Carefully read the documentation and write test cases to ensure the API behaves exactly as specified, especially for the permission part of the specification
2. Report any bugs (you are likely to find some) to `Yu Li#6257`

---------------

### Reward

chillin: 100
dcf +100xp

**Comment by roychen7** [comment]
i will finish this by this weekend
